import React from 'react';
import Link from 'next/link';

export default function TermsOfUsePage() {
  return (
    <>
      <h1 className="text-5xl mb-4">Terms of Use</h1>
      <p className="text-xl text-gray-400 font-light mb-12">
        Effective Date: November 14, 2025
      </p>

      <div className="bg-[#121214] p-6 border-l-2 border-[#3B82F6] rounded-r-sm mb-12 not-prose">
        <h4 className="text-white font-bold text-sm uppercase tracking-widest mb-2">Notice to Researchers</h4>
        <p className="text-sm text-gray-400 mb-0">
          If you are using Metanthropic services for commercial research, enterprise deployment, or API access, these terms do not apply to you. Please refer to our <Link href="/policies/commercial-terms" className="text-[#3B82F6] hover:underline">Commercial Terms of Service</Link>.
        </p>
      </div>

      <p>
        Thank you for using Metanthropic. These Terms of Use apply to your use of our consumer-facing interfaces, research demos, and "Glass Box" interpretability tools (collectively, the "Services").
      </p>

      <h3>1. Our Mission and Your Use</h3>
      <p>
        Metanthropic is an independent research laboratory dedicated to the physics of intelligence. Our mission is to build safe, interpretable, and verifiable artificial general intelligence. By using our Services, you agree to use them in a manner consistent with this mission.
      </p>
      <p>
        Unlike standard "Black Box" models, our systems generate "Thought Traces" that are auditable. <strong>You acknowledge that Metanthropic reserves the right to monitor these reasoning traces</strong> to ensure compliance with our safety constitution, even if the final output is benign.
      </p>

      <h3>2. Scientific Verification & Liability</h3>
      <p>
        <strong>The "Instrument" Clause.</strong> You understand that Metanthropic services are scientific instruments, not oracles of truth. While we strive for verifiability:
      </p>
      <ul>
        <li><strong>Verification Required:</strong> If you use our models for scientific publication, medical diagnosis, or code deployment, you are solely responsible for verifying the "Thought Trace" (the causal reasoning path) provided by the model.</li>
        <li><strong>No Reliability Warranty:</strong> Experimental models may produce plausible but incorrect assertions ("hallucinations"). You should not rely on the Services for critical advice without independent human review.</li>
      </ul>

      <h3>3. Content & Ownership</h3>
      <p>
        <strong>Your Content.</strong> You provide input to the Services ("Input"), and receive output generated by the Services ("Output"). Between you and Metanthropic, and to the extent permitted by applicable law, you own all Input.
      </p>
      <p>
        <strong>Model Weights.</strong> You acknowledge that while you own the Output, you acquire no rights to the underlying model weights, activations, or "Thought Trace" mechanisms used to generate that Output.
      </p>

      <h3>4. Restrictions</h3>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Services to develop foundation models or other large-scale models that compete with Metanthropic.</li>
        <li>Reverse assemble, reverse compile, or attempt to discover the source code of our interpretability tools.</li>
        <li>Use the Services to generate content that promotes deception, political misinformation, or biological harm (see <Link href="/policies/usage">Usage Policy</Link>).</li>
      </ul>

      <h3>5. Termination</h3>
      <p>
        We are a research lab first. We may suspend or terminate your access to the Services at any time if we believe your usage poses a safety risk, or if we are retiring a specific model checkpoint for safety reasons.
      </p>

    </>
  );
}
