import React from 'react';
import Link from 'next/link';

export default function CommercialTermsPage() {
  return (
    <>
      <h1>Commercial Terms of Service</h1>
      <p className="lead text-xl text-gray-400 font-light mb-8">
        Effective Date: November 14, 2025
      </p>

      <div className="bg-[#121214] border border-white/10 p-6 rounded-sm mb-12">
        <p className="mb-0 text-sm text-gray-300">
          <strong>Summary:</strong> These terms apply to enterprises, researchers, and developers using the Metanthropic API. Unlike our consumer terms, <strong>we do not use Commercial API data to train our foundation models</strong> by default.
        </p>
      </div>

      <h3>1. Service Usage & Grants</h3>
      <p>
        <strong>License.</strong> Subject to your compliance with these Terms, Metanthropic grants you a non-exclusive, non-transferable right to access and use our API and "Glass Box" interpretability tools (the "Services").
      </p>
      <p>
        <strong>Restrictions.</strong> You may not (i) use the Services to develop foundation models or other large scale models that compete with Metanthropic; (ii) attempt to reverse engineer the underlying weights or "Thought Trace" mechanisms; or (iii) use the Services for any High-Risk Use Case (as defined in our <Link href="/policies/usage">Usage Policy</Link>) without express written permission.
      </p>

      <h3>2. Data & Training</h3>
      <p>
        <strong>Input & Output.</strong> As between the parties, you retain all ownership rights in your Input, and you own all Output generated by the Services.
      </p>
      <p>
        <strong>No Training on API Data.</strong> Metanthropic does not use content submitted via our Commercial API to train or improve our foundation models. Your data remains isolated. We may, however, retain logs of "Thought Traces" for a limited period solely to monitor for safety and abuse (See "Safety & Compliance").
      </p>

      <h3>3. Safety & Compliance</h3>
      <p>
        <strong>The "Kill Switch".</strong> Metanthropic is a safety-first laboratory. We reserve the right to suspend or terminate your access immediately if we detect usage that violates our Safety Constitution, attempts to bypass alignment controls ("Jailbreaking"), or deploys our models for autonomous cyber-offensive tasks.
      </p>
      <p>
        <strong>Audit Rights.</strong> For deployments exceeding 1M requests/day, Metanthropic reserves the right to audit your integration to ensure safety guardrails are correctly implemented.
      </p>

      <h3>4. Service Level Agreements (SLA)</h3>
      <p>
        For Enterprise tier customers, we guarantee 99.9% monthly uptime. Credits are issued for downtime exceeding this threshold. Beta models and "Research Previews" are excluded from this SLA.
      </p>

      <h3>5. Indemnification</h3>
      <p>
        You will defend, indemnify, and hold harmless Metanthropic from and against any claims, losses, and expenses arising from your use of the Services, including any content you generate that violates third-party rights or applicable law.
      </p>
    </>
  );
}
