import React from 'react';

export default function PrivacyPolicyPage() {
  return (
    <>
      <h1 className="text-5xl mb-4">Privacy Policy</h1>
      <p className="text-xl text-gray-400 font-light mb-12">
        Effective Date: November 14, 2025
      </p>

      <p className="text-lg text-white mb-8">
        How we handle data in the era of interpretable intelligence.
      </p>

      <h3>1. Data We Collect</h3>
      <ul>
        <li><strong>Account Information:</strong> Name, email, and billing details.</li>
        <li><strong>Content:</strong> The inputs you provide and the outputs generated.</li>
        <li><strong>Technical Information:</strong> Browser type, IP address, and usage logs.</li>
        <li><strong>Reasoning Data:</strong> The internal &quot;Thought Traces&quot; (intermediate reasoning steps) generated by the model during your session.</li>
      </ul>

      <h3>2. How We Use Your Data</h3>
      <p>
        <strong>For Consumers (Free/Pro Plans):</strong> We may use your Content (inputs/outputs) to improve our models. You can opt-out of this training in your account settings.
      </p>
      <p>
        <strong>For Commercial/API Users:</strong> We <span className="text-white font-bold">do not</span> train on your Content. Your API data is used solely to provide the service.
      </p>
      <p>
        <strong>Safety Monitoring:</strong> For all users, we retain logs of &quot;Thought Traces&quot; for up to 30 days to monitor for safety violations (e.g., bio-weapon design attempts). This data is accessible only to our Safety Engineering team and is not used for general training.
      </p>

      <h3>3. Disclosure of Data</h3>
      <p>
        We do not sell your data. We share data only with:
      </p>
      <ul>
        <li><strong>Service Providers:</strong> Cloud hosting (AWS/GCP) and payment processors (Stripe).</li>
        <li><strong>Legal Requirements:</strong> If compelled by a valid subpoena or court order.</li>
      </ul>

      <h3>4. Security</h3>
      <p>
        We implement enterprise-grade encryption (AES-256) for data at rest and TLS 1.3 for data in transit. Our &quot;Glass Box&quot; architecture means we can audit exactly <em>how</em> a model accessed information, providing a layer of security auditing not present in standard LLMs.
      </p>

      <h3>5. Contact Us</h3>
      <p>
        For privacy concerns or GDPR/CCPA requests, please contact our Data Protection Officer at <a href="mailto:privacy@metanthropic.com">privacy@metanthropic.com</a>.
      </p>
    </>
  );
}
